server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080/auth/
  realm: km
  resource: client-app
  use-resource-role-mappings: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

binance:
  api:
    base-url: https://api.binance.com
    uri-prefix-with-version: /api/v3
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: prometheus, info, metrics
#        include: "*"
  server:
    port: 8085

---
spring:
  profiles: local
feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    pl:
      km:
        binance:
          api:
            infrastructure: DEBUG
---
spring:
  profiles: dev
server:
  port: 8082

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST}:8080/auth/

logging:
  level:
    org:
      springframework:
        security: DEBUG